name: Windows build testing
on: [push, pull_request]

jobs:
  job:
    name: windows-vs17
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          submodules: true
          fetch-depth: 0
      - uses: Jimver/cuda-toolkit@v0.2.10
        id: cuda-toolkit
        with:
          cuda: '12.1.0'
      - name: Configure
        run: cmake -B build
      - name: Build Debug
        run: cmake --build build --config Debug --verbose
      - name: Build Release
        run: cmake --build build --config Release --verbose
